### ISSUE TITLE
installing nodejs 0.10.* does not install npm, causing the provisioning to fail.

### ISSUE THREAD

**Issue by mveldman** [geerlingguy/ansible-role-nodejs#62] opened 2017-03-30 11:18 UTC
When the 'Ensure Node.js and npm are installed.' is run, and it installs 0.10.* (0.10.48 in my particular case) it installs node, but not npm.
That causes the 'Ensure npm global packages are installed.' step to fail.

Tested with geerlingguy/centos6 and centos7

**Comment by geerlingguy** [comment] 2017-03-30 20:45
Interesting; I haven't noticed this issue in the past, but I haven't installed 0.10.x in a long while (I'm on 4.x most places now, and testing 6.x).

I'm inclined to close / not fix this if it only affects 0.10.x, since that version isn't even supported by the Node.js community anymore. Can you reproduce this issue if you try 0.12, 4.x, or 6.x?

**Comment by mveldman** [comment] 2017-03-31 08:42
Thanks for the response.
I've done some more testing:
CentOS 6

0.10 Fails as described.
0.12 Fails in Add Nodesource repositories for Node.js (CentOS < 7) with http://rpm.nodesource.com/pub_0.12/el/6/x86_64/nodesource-release-el6-1.noarch.rpm
4.x Works, installs nodejs v4.8.1, npm 2.15.11
6.x Works, installs nodejs v6.10.1, npm 3.10.10

CentOS 7

0.10 Works, installs nodejs v0.10.46, npm 2.15.1
0.12 Fails in the same way as on CentOS 6
4.x Works, installs nodejs v4.8.1, npm 2.15.11
6.x Works, installs nodejs v6.10.1, npm 3.10.10

Perhaps worth mentioning somewhere:
You can only specify '4.x', '6.x' for nodejs_version. If you specify something like '6.10.1' it will fail in  
'Add Nodesource repositories for Node.js (CentOS 7+)'  with
Failure downloading https://rpm.nodesource.com/pub_6.10.1/el/7/x86_64/nodesource-release-el7-1.noarch.rpm.
And on CentOS at least, only the major version is used for determining what node version is installed anyway. I'll try and see if I can create a PR later.

**Comment by geerlingguy** [comment] 2017-03-31 12:06
@mveldman - Thanks so much for doing this debugging! It seems the nodesource repos for CentOS are not maintained nearly as well as the repos for Ubuntu/Debian :(

**Comment by s17t** [comment] 2018-06-26 06:02
It looks like the URL template is different for CentOS 7 and Node ~8.x
```
/el/7/x86_64/nodejs-{{nodejs_version}}-1nodesource.x86_64.rpm
```

**Comment by geerlingguy** [comment] 2019-01-03 15:54
I'm going to close this issue out, as it's been a while since 0.x releases were supported.

**Closed by geerlingguy** 2019-01-03 15:54 UTC
