### ISSUE TITLE
Install of Node.js 0.12 fails on CentOS 6

### ISSUE THREAD

**Issue by bendavies** [geerlingguy/ansible-role-nodejs#20] opened 2016-03-14 10:39 UTC
This looks to be the issue
https://github.com/nodesource/distributions/issues/240

**Comment by geerlingguy** [comment] 2016-03-14 17:06
Thanks @bendavies - this is (as you pointed out) an upstream bug in https://github.com/nodesource/distributions/issues/240. For now, my recommendations would be to use a different Node.js version (0.10 or 4.x would both work), or to switch to a CentOS 7 or Ubuntu base box; 0.12 is working in those.

I'd rather not hack things to work with 0.12 from 0.12, at least not yet...

**Comment by Crashtown** [comment] 2016-04-12 08:15
We already use CentOS 7 and faced with same issue
```
TASK [geerlingguy.nodejs : Add Nodesource repositories for Node.js.] ***********
FAILED! => {"changed": false, "failed": true, "msg": "Package at https://rpm.nodesource.com/pub_5.6/el/7/x86_64/nodesource-release-el7-1.noarch.rpm could not be installed", "rc": 1}
```

**Comment by oxyc** [comment] 2016-05-15 17:31
I can confirm this fails on CentOS 7 with v0.12. Over at Drupal VM that means the default setup does not work when toggle `nodejs` to install.

**Comment by geerlingguy** [comment] 2016-05-16 15:23
@oxyc - Thanks for confirming. Looks like we may want to update the default to 4.x or 5.x in the mean time. Nodesource's repos might not be the most stable for non-Debian (it seems they have preferential treatment for Deb-based repos).

**Comment by geerlingguy** [comment] 2016-06-06 20:05
It looks like this is resolved at least for CentOS 7 at this point... maybe not for CentOS 6 :/

See #8

**Comment by geerlingguy** [comment] 2016-06-06 20:06
I'm going to close this issue for now, as you can currently do a workaround (as described in https://github.com/nodesource/distributions/issues/240), and I'll just keep waiting for that upstream fix.

**Closed by geerlingguy** 2016-06-06 20:06 UTC
